---
name: mvn
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Tests
    strategy:
      matrix:
        # @todo #640:30min Enable Windows OS.
        #  To do so, you just need to add 'windows-2022' below.
        #  However, we can do it, because of the following problem:
        #  https://github.com/objectionary/eo/issues/3307
        #  After the problem is resolved, we can enable Windows OS.
        os: [ ubuntu-20.04, macos-12 ]
        java: [ 8, 11, 20 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: mvn clean install -P"qulice,long" --errors --batch-mode
      - name: Archive failure logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-log-files
          path: |
            target/**/build.log
